<?php
/**
 * Responsive Image Component
 *
 * Renders an optimized image with lazy loading, error handling, and accessibility.
 *
 * @var string $src        Image URL (required)
 * @var string $alt        Alt text (required for accessibility)
 * @var string $class      Additional CSS classes (optional)
 * @var string $loading    Loading strategy: 'lazy' (default) or 'eager'
 * @var bool   $decoding   Async decoding (default: true)
 * @var string $attributes Custom HTML attributes (optional)
 * @var array  $variants   Image variants generated by the hub (optional)
 * @var bool   $responsive Whether to emit responsive srcset candidates (default: true)
 * @var string $preferredVariant Preferred variant for the fallback src (optional)
 * @var string $sizes      CSS image display size hint (optional)
 * @var int    $maxVariantWidth Maximum candidate width for bounded slots (optional)
 */

$src = $src ?? '';
$alt = $alt ?? '';
$class = $class ?? '';
$decoding = $decoding ?? 'async';
$attributes = $attributes ?? '';
$variants = $variants ?? null;
$responsive = $responsive ?? true;
$preferredVariant = $preferredVariant ?? null;
$sizes = $sizes ?? null;
$maxVariantWidth = $maxVariantWidth ?? null;
$hideOnError = (bool) ($hideOnError ?? false);

if ($src === '') {
    return;
}

// Dynamically optimize performance based on image sequence order and device type
$imgIndex = \Config\Services::blockRenderer()->incrementImageCount();
$isMobile = \Config\Services::request()->getUserAgent()->isMobile();
$maxEager = $isMobile ? 1 : 4;
$loading = $loading ?? (($imgIndex <= $maxEager) ? 'eager' : 'lazy');
$fetchPriority = $fetchPriority ?? (($imgIndex === 1) ? 'high' : null);

$selectedImage = \App\Support\ImageVariantSelector::resolve(
    $src,
    $responsive ? $variants : null,
    is_string($preferredVariant) ? $preferredVariant : null,
    is_numeric($maxVariantWidth) && (int) $maxVariantWidth > 0 ? (int) $maxVariantWidth : null,
);
$src = $selectedImage['src'];
$srcsetString = $selectedImage['srcset'];
$sizesString = is_string($sizes) && trim($sizes) !== '' ? trim($sizes) : $selectedImage['sizes'];

if ($responsive && $srcsetString === '' && preg_match('#^https?://picsum\.photos/id/(\d+)/(\d+)/(\d+)(/?\?.*)?$#i', $src, $matches)) {
    $id = $matches[1];
    $width = (int) $matches[2];
    $height = (int) $matches[3];
    $query = $matches[4] ?? '';

    if ($width > 0 && $height > 0) {
        $ratio = $width / $height;
        $standardWidths = [480, 800, 1200];

        // Filter out widths larger than the original to avoid upscaling
        $widths = array_filter($standardWidths, static fn($w) => $w <= $width);

        // Ensure the original width is included
        if (empty($widths) || !in_array($width, $widths, true)) {
            $widths[] = $width;
        }
        sort($widths);

        $srcsetItems = [];
        foreach ($widths as $w) {
            $h = (int) round($w / $ratio);
            $srcsetItems[] = "https://picsum.photos/id/{$id}/{$w}/{$h}{$query} {$w}w";
        }

        $srcsetString = implode(', ', $srcsetItems);
        $sizesString = '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, ' . $width . 'px';
    }
}

if (($fetchPriority ?? null) === 'high') {
    \Config\Services::blockRenderer()->addPreload($src, $srcsetString, $sizesString);
}
?>
<img
    src="<?= esc($src) ?>"
    alt="<?= esc($alt) ?>"
    class="<?= esc($class) ?>"
    loading="<?= esc($loading) ?>"
    decoding="<?= esc($decoding) ?>"
    <?php if ($responsive && $srcsetString !== ''): ?>
        srcset="<?= esc($srcsetString) ?>"
        sizes="<?= esc($sizesString) ?>"
    <?php endif; ?>
    <?php if ($fetchPriority !== null): ?>
        fetchpriority="<?= esc($fetchPriority) ?>"
    <?php endif; ?>
    <?= $attributes ?>
    data-image-fallback="<?= $hideOnError ? 'hide' : 'fail' ?>"
    data-image-fallback-alt="<?= esc(lang('Site.image_failed_to_load'), 'attr') ?>"
>
